### ISSUE TITLE
Dar acesso as Big Kahunas da PyNE 2025 ao Bitwarden

### ISSUE THREAD

**Issue by itepifanio** [pythonNordeste/organizacao-pyne-2025#2]
Estamos discutindo ainda a mudança pro cofre de senha do 1password, mas o pessoal da edição 2025 quer ter acesso ao email para ir vendo o local e consequentemente a data.

Emails: anapaula.ds.mendes@gmail.com
            emillyhortapy@gmail.com

**Comment by cecivieira** [comment]
Obrigada por avisar, Ítalo.
Vamos marcar uma conversa com elas e daremos acesso.

**Comment by cecivieira** [comment]
@naanadr será que conseguiríamos migrar o chaveiro por 1Password antes de dar esse acesso?

https://github.com/apyb/comunidade/discussions/130
