### ISSUE TITLE
Kickoff com novas organizadoras

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/organizacao-pyne-2025#3]
Pautas:

- [x] Boas vindas
- [x] Apresentar o [Guia de Organização de eventos](https://apyb.python.org.br/associados/guias/como-organizar-eventos/)
- [x] Formulário de cadastro do evento junto a APyB
- [x] Sistema financeiro (como acompanhar mensalmente o saldo) + sugestão de acompanhamento interno da organização 
- [x] Apresentação do chaveiro 1Password
- [x] Comunicação sugerida (transparente no github) + Como se comunicar com APyB (github)

**Comment by cecivieira** [comment]
@anapaulamendes @Emilly-horta bora conversar semana que vem a noite?

@buxbaum estou marcando vocês para fazermos a mesma reunião com todas as orgs que tão começando, ao mesmo tempo.

Proposta de data:
27/08 às 19h (GMT -3)

**Comment by cecivieira** [comment]
Cc @jeanmask

**Comment by cecivieira** [comment]
Qual é o e-mail de vocês, para que eu coloque no calendário @anapaulamendes @Emilly-horta @jeanmask @buxbaum


Link da videochamada: https://meet.google.com/ntq-pkyv-fsk

**Comment by anapaulamendes** [comment]
>Qual é o e-mail de vocês, para que eu coloque no calendário @anapaulamendes @Emilly-horta @jeanmask @BuxBaum

anapaula.ds.mendes@gmail.com

**Comment by BuxBaum** [comment]
Hey
You guys might have tagged the wrong person.
I have no affiliation with pythonNordeste

**Comment by cecivieira** [comment]
@jeanmask qual é o @ do outro big kahuna da PySE?

@BuxBaum sorry

**Comment by jeanmask** [comment]
O dia sugerido do 27/08 as 19h eu não posso, caso o @vbuxbaum possa participar já é suficiente e caso seja possível gravar a reunião seria ótimo :)

**Comment by vbuxbaum** [comment]
Bom dia pessoal! 😁

Confirmado!
Meu email é vitorbuxbaum@gmail.com

**Comment by vbuxbaum** [comment]
Boa tarde @cecivieira! Tudo joia?

Quando puder coloca o link da gravação aqui por favor? O invite ainda não aparece no meu calendar 😢

**Comment by cecivieira** [comment]
@naanadr tu poderia migrar esse vídeo para o drive da apyb e colocar aqui um novo link?

@vbuxbaum o link temporário é esse : https://drive.google.com/file/d/1UeAkP-7iHNyg14jOQr6ynW5uPNR2caO0/view?usp=sharing

**Comment by naanadr** [comment]
@cecivieira eu não consigo baixar o video, só fazer um atalho 😢

**Comment by cecivieira** [comment]
@naanadr te coloquei como editora. Vê se tu consegue agora

**Comment by naanadr** [comment]
@cecivieira consegui baixar e salvei no drive da APyB, também criei uma issue para adicionar esse vídeo na nossa documentação (https://github.com/apyb/tarefas/issues/923)

**Comment by cecivieira** [comment]
Obrigada @naanadr !!!
Apaguei o vídeo do meu drive
