### ISSUE TITLE
Chamada de patrocinadoras

### ISSUE THREAD

**Issue by anapaulamendes** [pythonNordeste/organizacao-pyne-2025#7]
Quando o plano de patrocínio tiver concluído, precisamos fazer uma chamada nas redes sociais.

- [x] Arte
- [x] Texto para as mídias
- [x] Publicar

**Comment by jjpaulo2** [comment]
Publicamos em todas as redes sociais ontem (28/10/2024).

@anapaulamendes mais algo pendente pra que a gente mantenha essa issue aberta?
